language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt-preview
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - gcc-5
      - g++-5
      - clang-5.0
      - clang-5.0-dev
cache:
  apt: true

install:
  - .ci-script/travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH

script:
  # For speed up the CI process
  #   See: https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs
  - cargo fmt -- --write-mode check && cargo build --all-features --all && cargo test --all-features --all
